bitbake.conf: Switch prefix mapping to use -ffile-prefix-map
Issue: LIN1025-645

The maximum allowed TMPDIR length in Poky is currently 400 characters.
However, building of lib32-gcc failed at 399 characters with the following
error:

make: /bin/bash: Argument list too long
make: *** [Makefile:4701: all-gcc] Error 127
ERROR: oe_runmake failed

This issue has been resolved in LINCD. In LTS25, both -fdebug-prefix-map
and -fmacro-prefix-map options were used, which caused mapped path
to be passed twice on the command line. Replacing these with the single
 -ffile-prefix-map option which is a superset of both reduces the
command-line length and avoids the above error.

(cherry-picked from oe-core rev: ff73fa7ef7666a6dbe34f15515bc3ab6e574c5b0)

(LOCAL REV: NOT UPSTREAM) -- Not applicable, upstream out of maintenance

Signed-off-by: Deepesh Varatharajan <Deepesh.Varatharajan@windriver.com>