barebox-tools: clean up yamltree from dtc
Refer Linux commit [dt-bindings: kbuild: Use DTB files for validation][1],
clean up yamltree from dtc to avoid compile failure while include <yaml.h>
in non-standard path

| tmp/work/core2-64-wrs-linux/barebox-tools/2025.02.0/barebox-2025.02.0/scripts/
dtc/yamltree.c:9:10: fatal error: yaml.h: No such file or directory
|     9 | #include <yaml.h>

Since barebox actually doesn't do any dtb binding checks at the moment, just
remove the test of /usr/include/yaml.h, hard-code the -DNO_YAML and remove
yamltree.c from DTC_SOURCE

[1] https://github.com/torvalds/linux/commit/ef8795f3f1ce

(LOCAL REV: NOT UPSTREAM) -- send to oe-core on 20250407
Issue: LINCD-23385

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>