shadow: disable econf
Issue: LIN1025-5845

On opensuse 16.0, when libeconf is installed and extend buildtools gcc
is used, libeconf on host is found, but libeconf.h on host cannot be
found by gcc, so native shadow do_compile failed:
../../shadow-4.17.3/lib/getdef.c:22:10: fatal error: libeconf.h: No such file or directory

disable econf to fix above failure

(LOCAL REV: NOT UPSTREAM) -- upstream Walnascar EOL

Signed-off-by: Changqing Li <changqing.li@windriver.com>