lttng-modules: fix trace_hrtimer_start conflicting types since kernel 6.12.91
Issue: LIN1025-15550

Kernel 6.12.91 added a 'was_armed' parameter to the trace_hrtimer_start,
causing a build failure:
  error: conflicting types for 'trace_hrtimer_start';
  have 'void(struct hrtimer *, enum hrtimer_mode)'
  previous definition: 'void(struct hrtimer *, enum hrtimer_mode, bool)'

Signed-off-by: Haixiao Yan <haixiao.yan.cn@windriver.com>