Revert "kernel: drop 6.6 reference kernels"
This reverts commit 6c445a6995f810e48a25cc0c13f37271836cba00.

Issue: LINUXEXEC-33907

Add linux-yocto 6.6 back to avoid following errors temporarily:

ERROR: No recipes in default available for:
  /path_to/layers/intel-x86/recipes-kernel/linux/linux-yocto-rt_6.6.bbappend
  /path_to/layers/intel-x86/recipes-kernel/linux/linux-yocto_6.6.bbappend
  /path_to/layers/bcm-2xxx-rpi/recipes-kernel/linux/linux-yocto-rt_6.6.bbappend
  /path_to/layers/bcm-2xxx-rpi/recipes-kernel/linux/linux-yocto_6.6.bbappend
  /path_to/layers/amd-zynqmp/recipes-kernel/linux/linux-yocto_6.6.bbappend

(LOCAL REV: NOT UPSTREAM) -- WRLinux specific

Signed-off-by: Kai Kang <kai.kang@windriver.com>