qemu: disable libkeyutils
Issue: LIN1025-6456

When package keyutils-devel is installed on host and gcc in extend buildtools
is used, qemu-system-native do_compile failed with error:
../qemu-9.2.0/backends/cryptodev-lkcf.c:36:10: fatal error: keyutils.h: No such file or directory*

 36    #include <keyutils.h>

                ^~~~~~~~~~~~

gcc in extend buildtools can find libkeyutil on the host, but it will not
search the headers on the host cause above issue. add PACKAGECONFIG
libkeyutils, and disable libkeyutils by default to fix the issue

(LOCAL REV: NOT UPSTREAM) -- Not applicable, upstream out of maintenance

Signed-off-by: Changqing Li <changqing.li@windriver.com>